name: torrent_frontend
description: Frontend torrent client
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  fl_chart: ^0.62.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.3.6
  json_annotation: ^4.8.1
  responsive_grid_list: ^1.3.2
  simple_grid: ^0.1.2
  transmission_rpc:
    path: /home/flafy/repos/flafydev/transmission_rpc

dev_dependencies:
  very_good_analysis: ^5.0.0+1
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2
  build_runner: ^2.4.6
  freezed: ^2.3.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
