name: torrent_frontend
description: Frontend torrent client
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  fl_chart: ^0.62.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6

dev_dependencies:
  very_good_analysis: ^5.0.0+1
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2

flutter:
  uses-material-design: true
